// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    first_name,
    last_name,
    birth_date,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    first_name,
    last_name,
    birth_date,
    email,
    created_at
`

type CreateMemberParams struct {
	FirstName string
	LastName  string
	BirthDate pgtype.Date
	Email     pgtype.Text
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Email,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
