// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Member struct {
	ID        int32
	FirstName string
	LastName  string
	BirthDate pgtype.Date
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
}
