// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    first_name,
    last_name,
    birth_date,
    phone_number,
    email,
    address
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, first_name, last_name, birth_date, phone_number, email, address, created_at
`

type CreatePersonParams struct {
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Address     pgtype.Text
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, first_name, last_name, birth_date, phone_number, email, address, created_at
FROM persons
WHERE id = $1
`

func (q *Queries) GetPersonByID(ctx context.Context, id int32) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const listPersons = `-- name: ListPersons :many
SELECT id, first_name, last_name, birth_date, phone_number, email, address, created_at
FROM persons
ORDER BY last_name, first_name
`

func (q *Queries) ListPersons(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.PhoneNumber,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET 
    first_name = $2,
    last_name = $3,
    birth_date = $4,
    phone_number = $5,
    email = $6,
    address = $7
WHERE id = $1
RETURNING id, first_name, last_name, birth_date, phone_number, email, address, created_at
`

type UpdatePersonParams struct {
	ID          int32
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Address     pgtype.Text
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
