// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    first_name,
    last_name,
    birth_date,
    phone_number,
    email,
    address
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, first_name, last_name, birth_date, phone_number, email, address, created_at
`

type CreatePersonParams struct {
	FirstName   string
	LastName    string
	BirthDate   pgtype.Date
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Address     pgtype.Text
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
